---

- name: Copy nux-misc repo
  copy:
    src: nux-misc.repo
    dest: /etc/yum.repos.d/nux-misc.repo
    owner: root
    group: root
    mode: 0644

- name: Install tac_plus
  yum:
    name: tac_plus
    enablerepo: nux-misc
    state: present

- name: Enable tac_plus
  service:
    name: tac_plus
    enabled: yes

- name: Copy tacacas config
  template:
    src: tac_plus.conf.j2
    dest: /etc/tac_plus.conf
    owner: root
    group: root
    mode: 0640
  notify: restart tac_plus
